/**
 * Script to update all card descriptions with longer versions.
 * Replace placeholder content with your chosen card meanings as needed.
 */

const fs = require('fs');
const path = require('path');

const cardsFile = path.join(__dirname, 'apps/mobile/src/data/tarot/cards.json');
const cards = JSON.parse(fs.readFileSync(cardsFile, 'utf8'));

// Extended descriptions for each card (replace with your chosen content as needed)
const extendedDescriptions = {
  "empress": "The Empress represents femininity, beauty, nature, nurturing, and abundance. She is the mother figure, a symbol of fertility and growth. When The Empress appears in a reading, it often signifies a time of creativity, abundance, and nurturing energy. This card encourages you to connect with nature and to embrace your feminine power, whether you are male or female. The Empress represents the fertile ground from which all things grow, and she reminds us to nurture our dreams and ideas until they come to fruition. She is associated with sensuality, beauty, and the pleasures of life, encouraging you to enjoy the material world while also maintaining a connection to the natural world. This card suggests that you may be entering a period of growth and expansion, whether in your personal life, career, or creative endeavors. The Empress reminds you to be patient and to trust in the natural cycles of life, knowing that everything has its time to bloom.",
  
  "emperor": "The Emperor represents authority, establishment, structure, and a father figure. He is a symbol of stability, power, and protection. When The Emperor appears in a reading, it suggests that you need to take a more structured and disciplined approach to your life. This card represents the establishment of order and the creation of solid foundations upon which to build your future. The Emperor encourages you to take responsibility for your actions and to lead with confidence and authority. He represents the masculine principle of action and control, reminding you that you have the power to shape your own destiny through discipline and determination. This card suggests that you may need to set clear boundaries and establish rules in your life, whether in your relationships, career, or personal development. The Emperor reminds you that true power comes from within and that you can achieve your goals through focused effort and strategic planning.",
  
  "hierophant": "The Hierophant represents spiritual wisdom, religious beliefs, conformity, and tradition. He is a teacher and a guide to higher knowledge. When The Hierophant appears in a reading, it suggests that you may be seeking guidance from established institutions or traditional sources of wisdom. This card represents the search for meaning and the desire to understand the deeper truths of life. The Hierophant encourages you to learn from those who have come before you and to respect the wisdom of tradition while also finding your own path. He represents the bridge between the spiritual and material worlds, showing you how to integrate higher knowledge into your daily life. This card suggests that you may be going through a period of learning or spiritual growth, and that you should seek out teachers or mentors who can guide you on your path. The Hierophant reminds you that there is value in tradition and established knowledge, but that you should also trust your own inner wisdom.",
  
  "lovers": "The Lovers represents love, harmony, relationships, and values alignment. It also signifies important choices and the union of opposites. When The Lovers appears in a reading, it often indicates a significant relationship or partnership in your life. This card represents the coming together of two forces, whether they be two people, two ideas, or two aspects of yourself. The Lovers encourages you to make choices based on your values and to align your actions with what truly matters to you. This card suggests that you may be facing an important decision that requires you to choose between two paths, and that you should follow your heart while also considering the consequences of your choice. The Lovers represents the balance between love and desire, and reminds you that true love requires both passion and commitment. This card encourages you to be authentic in your relationships and to seek partnerships that are based on mutual respect and shared values.",
  
  "chariot": "The Chariot represents control, willpower, success, and determination. It signifies overcoming obstacles through focus and discipline. When The Chariot appears in a reading, it suggests that you have the strength and determination to overcome any challenges that stand in your way. This card represents the power of focused intention and the ability to harness opposing forces to achieve your goals. The Chariot encourages you to stay focused on your objectives and to use your willpower to push through any obstacles. It represents the triumph of the human spirit over adversity, showing that you can achieve great things when you combine determination with clear direction. This card suggests that you may be in a position where you need to take control of a situation and to assert your will in order to move forward. The Chariot reminds you that success requires both inner strength and outer action, and that you must be willing to take risks and make sacrifices to achieve your goals.",
  
  "strength": "Strength represents inner strength, courage, persuasion, and compassion. It shows that true power comes from within, not from force. When Strength appears in a reading, it suggests that you have the inner resources to handle whatever challenges come your way. This card represents the power of gentleness and the ability to overcome obstacles through patience and compassion rather than aggression. Strength encourages you to trust in your own abilities and to approach difficult situations with calm confidence. It represents the balance between power and restraint, showing that true strength comes from knowing when to act and when to wait. This card suggests that you may be facing a situation that requires you to be patient and to use your inner strength to overcome obstacles. Strength reminds you that you are capable of handling whatever comes your way, and that you should approach challenges with a calm and confident attitude.",
  
  "hermit": "The Hermit represents soul searching, introspection, and inner guidance. It suggests a time for reflection and seeking answers within. When The Hermit appears in a reading, it often indicates a period of withdrawal and introspection. This card represents the need to step away from the noise and distractions of the outer world in order to find clarity and wisdom within. The Hermit encourages you to take time for solitude and reflection, and to trust in your own inner guidance. He represents the wise teacher who has learned through experience and who now shares that wisdom with others. This card suggests that you may be going through a period of questioning and seeking deeper meaning in your life. The Hermit reminds you that the answers you seek are already within you, and that you need only to quiet your mind and listen to your inner voice. It's a time to be patient and to trust that clarity will come when you are ready to receive it.",
  
  "wheel_of_fortune": "The Wheel of Fortune represents cycles, destiny, and karma. It reminds us that life is constantly changing and that what goes around comes around. When The Wheel of Fortune appears in a reading, it suggests that you are entering a period of change and transformation. This card represents the cyclical nature of life and the understanding that all things are in a constant state of flux. The Wheel of Fortune encourages you to accept the changes that are coming and to trust that they are part of a larger cycle that will ultimately bring balance and harmony. It represents the idea that our actions have consequences and that we will reap what we sow. This card suggests that you may be experiencing a turning point in your life, where things are beginning to shift in a new direction. The Wheel of Fortune reminds you that change is inevitable and that you should embrace it rather than resist it, knowing that every ending is also a new beginning.",
  
  "justice": "Justice represents fairness, truth, and cause and effect. It reminds us that our actions have consequences and that balance will be restored. When Justice appears in a reading, it suggests that you may be dealing with issues of fairness, truth, or accountability. This card represents the need to make decisions based on objective reasoning and to consider the consequences of your actions. Justice encourages you to be honest with yourself and others, and to take responsibility for your choices. It represents the idea that truth will always come to light and that justice will be served, even if it takes time. This card suggests that you may be in a situation where you need to make a fair and balanced decision, or where you are seeking justice for a past wrong. Justice reminds you that every action has a reaction, and that you should act with integrity and fairness in all your dealings.",
  
  "hanged_man": "The Hanged Man represents pause, surrender, and new perspectives. It suggests letting go of control and seeing things from a different angle. When The Hanged Man appears in a reading, it often indicates a period of waiting and suspension. This card represents the need to let go of your usual way of thinking and to see things from a completely different perspective. The Hanged Man encourages you to surrender to the present moment and to accept that sometimes the best action is inaction. He represents the wisdom that comes from seeing things from a new angle, and the understanding that sometimes we need to sacrifice something in order to gain something greater. This card suggests that you may be in a situation where you feel stuck or unable to move forward, and that you need to change your perspective in order to find a solution. The Hanged Man reminds you that sometimes the answer is to let go and trust in the process, even when it doesn't make sense from your current viewpoint.",
  
  "death": "Death represents endings, change, and transformation. It signifies the natural cycle of life and the need to let go of the old to make way for the new. When Death appears in a reading, it often indicates a significant ending or transformation in your life. This card represents the inevitability of change and the understanding that all things must come to an end in order for new things to begin. Death encourages you to let go of what no longer serves you and to embrace the transformation that is taking place. It represents the shedding of old patterns, beliefs, or relationships that are holding you back, and the emergence of something new and better. This card suggests that you may be going through a period of profound change, and that you should trust in the process even when it feels difficult or painful. Death reminds you that endings are necessary for new beginnings, and that transformation is a natural part of life's cycle.",
  
  "temperance": "Temperance represents balance, moderation, and patience. It reminds us to find harmony in all aspects of life and to act with purpose. When Temperance appears in a reading, it suggests that you need to find balance in your life and to avoid extremes. This card represents the art of moderation and the ability to blend different elements together in a harmonious way. Temperance encourages you to be patient and to take a measured approach to your goals, rather than rushing ahead or acting impulsively. It represents the balance between different aspects of your life, such as work and play, or logic and emotion. This card suggests that you may be dealing with conflicting forces or desires, and that you need to find a way to integrate them rather than choosing one over the other. Temperance reminds you that true success comes from finding balance and harmony in all areas of your life, and that patience and moderation are key to achieving your goals.",
  
  "devil": "The Devil represents shadow self, attachment, and restriction. It suggests being bound by material concerns or unhealthy patterns. When The Devil appears in a reading, it often indicates that you are feeling trapped or restricted in some way. This card represents the things that bind us and hold us back, whether they be addictions, unhealthy relationships, or limiting beliefs. The Devil encourages you to examine what is holding you captive and to recognize that you have the power to break free. It represents the shadow side of human nature and the temptations that can lead us astray. This card suggests that you may be dealing with issues of control, addiction, or unhealthy attachments, and that you need to confront these issues in order to move forward. The Devil reminds you that you are not truly trapped, and that you have the power to break free from whatever is holding you back, but that you must first recognize and acknowledge the chains that bind you.",
  
  "tower": "The Tower represents sudden change, upheaval, and revelation. It signifies the breakdown of false structures and the awakening to truth. When The Tower appears in a reading, it often indicates a sudden and dramatic change that shakes the foundations of your life. This card represents the destruction of false beliefs, structures, or situations that are no longer serving you. The Tower encourages you to embrace the chaos and to see it as an opportunity for growth and transformation. It represents the lightning bolt of truth that strikes suddenly and without warning, shattering illusions and revealing reality. This card suggests that you may be experiencing a crisis or upheaval that is forcing you to confront truths that you have been avoiding. The Tower reminds you that sometimes destruction is necessary for creation, and that the breakdown of old structures makes way for new and better ones. It's a time to let go of what no longer serves you and to rebuild on a more solid foundation.",
  
  "star": "The Star represents hope, faith, and renewal. It brings a sense of peace and inspiration after a difficult period. When The Star appears in a reading, it suggests that you are entering a period of healing and renewal. This card represents the light that shines in the darkness, offering hope and guidance when you need it most. The Star encourages you to have faith in the future and to trust that better times are ahead. It represents the connection between the earthly and the divine, and the understanding that we are all part of something greater than ourselves. This card suggests that you may be recovering from a difficult period and that you are beginning to see the light at the end of the tunnel. The Star reminds you to keep hope alive and to trust in the process of healing and renewal. It's a time to be gentle with yourself and to allow yourself to heal at your own pace, knowing that brighter days are coming.",
  
  "moon": "The Moon represents illusion, fear, and the subconscious. It suggests navigating through uncertainty and trusting your intuition. When The Moon appears in a reading, it often indicates a period of confusion or uncertainty. This card represents the realm of the subconscious mind and the fears and illusions that can cloud our judgment. The Moon encourages you to trust your intuition and to look beyond the surface of things to find the deeper truth. It represents the need to navigate through the darkness and uncertainty, trusting that you will find your way even when the path is not clear. This card suggests that you may be dealing with fears, anxieties, or illusions that are preventing you from seeing things clearly. The Moon reminds you that not everything is as it seems, and that you need to look deeper to find the truth. It's a time to trust your instincts and to pay attention to your dreams and intuition, as they may hold important messages for you.",
  
  "sun": "The Sun represents positivity, fun, warmth, and success. It brings joy, vitality, and a sense of accomplishment. When The Sun appears in a reading, it suggests that you are entering a period of happiness and success. This card represents the joy and vitality that comes from living in alignment with your true self. The Sun encourages you to embrace life with enthusiasm and to enjoy the simple pleasures that bring you happiness. It represents the warmth and light that comes from within, and the understanding that true happiness comes from being authentic and true to yourself. This card suggests that you may be experiencing a period of growth and expansion, where everything seems to be going your way. The Sun reminds you to celebrate your successes and to share your joy with others. It's a time to be optimistic and to trust that good things are coming your way, and to enjoy the present moment with gratitude and appreciation.",
  
  "judgement": "Judgement represents reflection, evaluation, and awakening. It calls for self-assessment and the opportunity for renewal. When Judgement appears in a reading, it suggests that you are being called to reflect on your life and to make important decisions about your future. This card represents the moment of reckoning when you must face the consequences of your past actions and make choices about how to move forward. Judgement encourages you to be honest with yourself and to take responsibility for your life. It represents the awakening to your true purpose and the understanding that you have the power to change your life for the better. This card suggests that you may be at a crossroads where you need to make important decisions about your future, and that you should take time to reflect on what truly matters to you. Judgement reminds you that you have the power to transform your life, but that you must first be willing to face the truth about yourself and your situation.",
  
  "world": "The World represents completion, accomplishment, and fulfillment. It signifies the successful conclusion of a journey and a sense of wholeness. When The World appears in a reading, it suggests that you have reached a significant milestone or completed an important phase in your life. This card represents the culmination of your efforts and the achievement of your goals. The World encourages you to celebrate your successes and to recognize how far you have come. It represents the integration of all aspects of yourself and the understanding that you are complete and whole just as you are. This card suggests that you may be experiencing a sense of fulfillment and accomplishment, and that you are ready to move on to the next phase of your journey. The World reminds you that every ending is also a beginning, and that you should take time to appreciate what you have achieved before moving forward. It's a time to feel proud of yourself and to recognize the growth and transformation that you have undergone.",
  
  "ace_wands": "The Ace of Wands represents new beginnings, inspiration, and creative energy. It brings the spark of passion and the will to start something new. When The Ace of Wands appears in a reading, it suggests that you are about to embark on a new creative project or venture. This card represents the initial spark of inspiration that ignites your passion and motivates you to take action. The Ace of Wands encourages you to follow your creative impulses and to trust in your ability to bring your ideas to life. It represents the raw energy and enthusiasm that comes with starting something new, and the excitement of embarking on a new adventure. This card suggests that you may be feeling inspired and motivated to pursue a new goal or project. The Ace of Wands reminds you that you have the power to create something new and exciting, and that you should trust in your creative abilities and take the first step toward your goals.",
  
  "two_wands": "The Two of Wands represents planning and taking the first steps toward your goals. It suggests looking ahead and making strategic decisions. When The Two of Wands appears in a reading, it suggests that you are in the planning phase of a new venture or project. This card represents the need to look ahead and to consider the long-term implications of your decisions. The Two of Wands encourages you to be strategic in your approach and to think carefully about the steps you need to take to achieve your goals. It represents the balance between planning and action, and the understanding that careful planning is essential for success. This card suggests that you may be feeling ready to take action but are still in the process of planning and preparing. The Two of Wands reminds you that it's important to have a clear vision of where you want to go, and to take the time to plan your journey before you begin.",
  
  "three_wands": "The Three of Wands represents looking ahead and expansion. It suggests your plans are taking shape and growth is on the horizon. When The Three of Wands appears in a reading, it suggests that you are beginning to see the results of your efforts and that your plans are starting to come to fruition. This card represents the expansion of your horizons and the opportunities that are opening up before you. The Three of Wands encourages you to look ahead with optimism and to trust that your efforts will be rewarded. It represents the growth and expansion that comes from taking action and moving forward with your plans. This card suggests that you may be experiencing a period of growth and expansion, where new opportunities are presenting themselves. The Three of Wands reminds you to stay focused on your goals and to continue moving forward with confidence, knowing that you are on the right path.",
  
  "ace_cups": "The Ace of Cups represents new feelings, love, and emotional beginnings. It brings the gift of intuition and spiritual connection. When The Ace of Cups appears in a reading, it suggests that you are opening your heart to new emotional experiences. This card represents the overflowing of love and emotion, and the beginning of a new emotional journey. The Ace of Cups encourages you to be open to love and to allow yourself to feel deeply. It represents the connection between the heart and the spirit, and the understanding that love is the most powerful force in the universe. This card suggests that you may be experiencing new feelings or opening yourself up to new emotional experiences. The Ace of Cups reminds you that love is always available to you, and that you should allow yourself to receive and give love freely. It's a time to be open to new emotional connections and to trust in the power of love to transform your life.",
  
  "two_cups": "The Two of Cups represents unity, partnership, and connection. It signifies a harmonious relationship based on mutual respect and attraction. When The Two of Cups appears in a reading, it suggests that you are forming or strengthening a significant relationship. This card represents the coming together of two people in a harmonious and balanced partnership. The Two of Cups encourages you to be open to connection and to value the relationships in your life. It represents the mutual exchange of love and support, and the understanding that true partnership is based on equality and respect. This card suggests that you may be entering into a new relationship or deepening an existing one. The Two of Cups reminds you that relationships require mutual effort and that both parties must be willing to give and receive love. It's a time to celebrate the connections in your life and to nurture the relationships that bring you joy and fulfillment.",
  
  "three_cups": "The Three of Cups represents friendship, community, and celebrations. It suggests coming together with others in joy and collaboration. When The Three of Cups appears in a reading, it suggests that you are experiencing a period of social connection and celebration. This card represents the joy that comes from being part of a community and the happiness that comes from sharing experiences with others. The Three of Cups encourages you to celebrate your friendships and to appreciate the people in your life who support and uplift you. It represents the power of collaboration and the understanding that we are stronger together than we are alone. This card suggests that you may be experiencing a period of social connection and that you should take time to celebrate with friends and loved ones. The Three of Cups reminds you that life is meant to be shared, and that the connections you have with others are one of life's greatest gifts.",
  
  "ace_swords": "The Ace of Swords represents breakthrough, clarity, and mental sharpness. It brings the power of truth and clear thinking. When The Ace of Swords appears in a reading, it suggests that you are experiencing a moment of clarity or breakthrough. This card represents the power of truth and the ability to cut through confusion and illusion. The Ace of Swords encourages you to think clearly and to speak your truth with confidence. It represents the sharpness of the mind and the ability to see things as they really are. This card suggests that you may be gaining new insights or understanding something that was previously unclear. The Ace of Swords reminds you that truth is powerful and that you should not be afraid to speak your mind or to stand up for what you believe in. It's a time to trust in your ability to think clearly and to use your intellect to solve problems and make decisions.",
  
  "two_swords": "The Two of Swords represents difficult choices and indecision. It suggests being at a crossroads and needing to make a decision. When The Two of Swords appears in a reading, it suggests that you are facing a difficult decision and are feeling stuck or unable to choose. This card represents the paralysis that can come from overthinking and the fear of making the wrong choice. The Two of Swords encourages you to trust your intuition and to make a decision, even if you don't have all the information you would like. It represents the need to balance logic and emotion, and to find a way forward even when the path is not clear. This card suggests that you may be avoiding a decision because you are afraid of the consequences, but that you need to make a choice in order to move forward. The Two of Swords reminds you that sometimes the best decision is to make a decision, and that you can always adjust your course later if needed.",
  
  "three_swords": "The Three of Swords represents heartbreak and emotional pain. It signifies a period of sorrow that requires healing and release. When The Three of Swords appears in a reading, it suggests that you are experiencing emotional pain or heartbreak. This card represents the pain that comes from loss, betrayal, or disappointment, and the need to process and heal from these experiences. The Three of Swords encourages you to allow yourself to feel your emotions and to grieve what you have lost. It represents the understanding that pain is a natural part of life and that healing takes time. This card suggests that you may be going through a difficult emotional period, but that this pain will eventually pass. The Three of Swords reminds you that it's okay to feel sad and to take time to heal, and that you will eventually find peace and happiness again. It's a time to be gentle with yourself and to allow yourself to process your emotions without judgment.",
  
  "ace_pentacles": "The Ace of Pentacles represents opportunity, prosperity, and new ventures. It brings the promise of material success and abundance. When The Ace of Pentacles appears in a reading, it suggests that you are being presented with a new opportunity for material gain or success. This card represents the seed of prosperity and the potential for financial growth and stability. The Ace of Pentacles encourages you to recognize and seize the opportunities that are presenting themselves to you. It represents the connection between effort and reward, and the understanding that you can create abundance in your life through hard work and smart choices. This card suggests that you may be entering a period of financial growth or that new opportunities for material success are opening up. The Ace of Pentacles reminds you that prosperity is available to you, but that you must be willing to work for it and to make smart decisions about how to use your resources. It's a time to be open to new opportunities and to trust that you have the ability to create abundance in your life.",
  
  "two_pentacles": "The Two of Pentacles represents priorities and adapting to change. It suggests juggling responsibilities and finding balance. When The Two of Pentacles appears in a reading, it suggests that you are juggling multiple responsibilities and trying to find balance in your life. This card represents the need to prioritize and to manage your time and resources effectively. The Two of Pentacles encourages you to be flexible and adaptable, and to find creative ways to balance competing demands. It represents the understanding that life is constantly changing and that you need to be able to adapt to new circumstances. This card suggests that you may be feeling overwhelmed by your responsibilities, but that you have the ability to manage them if you prioritize and stay organized. The Two of Pentacles reminds you that balance is key, and that you should not neglect any important area of your life. It's a time to be flexible and to find creative solutions to the challenges you are facing.",
  
  "three_pentacles": "The Three of Pentacles represents teamwork and collaboration. It suggests working together toward a common goal and learning from others. When The Three of Pentacles appears in a reading, it suggests that you are working with others to achieve a common goal. This card represents the power of collaboration and the understanding that we can achieve more together than we can alone. The Three of Pentacles encourages you to value the contributions of others and to be open to learning from those who have more experience or expertise. It represents the importance of working together and the satisfaction that comes from creating something as a team. This card suggests that you may be part of a collaborative project or that you are learning from a mentor or teacher. The Three of Pentacles reminds you that everyone has something valuable to contribute, and that you should be open to both giving and receiving help. It's a time to appreciate the power of teamwork and to recognize that success is often a collaborative effort."
};

// Update all cards with extended descriptions
cards.forEach(card => {
  if (extendedDescriptions[card.id]) {
    card.description = extendedDescriptions[card.id];
  }
});

// Write back to file
fs.writeFileSync(cardsFile, JSON.stringify(cards, null, 2), 'utf8');
console.log(`✅ Updated ${cards.length} cards with longer descriptions`);
console.log('Note: Replace placeholder descriptions with your chosen content as needed.');

